### ISSUE TITLE
install

### ISSUE THREAD

**Issue by kilometer0101** [aratakokubun/GraphBasedSegmentationWithUnionFind#1]
qiitaから来ました。
興味があって使ってみたいのですが、

pip install git+URL

でインストールできますでしょうか？
手元では、Anaconda 4.3.1を使っていますが、setup.py egg_info: でエラーがで出てしまいます。

    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/Users/km/anaconda/lib/python3.6/tokenize.py", line 452, in open
        buffer = _builtin_open(filename, 'rb')
    FileNotFoundError: [Errno 2] No such file or directory: '/private/var/folders/nk/plk5zj6941sgpvrpvq2h5l500000gn/T/pip-3tbs8wio-build/setup.py'

ご示唆いただけますでしょうか。
当方、Python素人な質問で申し訳在りません。

＞ ごめんなさい、解決しました。。Python使え使えハラスメント(パイハラ)おそるべし、です。

**Comment by aratakokubun** [comment]
ご連絡ありがとうございます。
興味をもっていただいて嬉しいです！

結論としては、pipコマンドではインストールできません。
git cloneしたのち、readmeの通りプログラムを実行してみて下さい。

理由はインストールできる形式にしていないためで、pip install gitなどで調べてみる詳しい理由もわかるかと思います。
（自分もまだ初学者で、目下勉強中です・・・）

是非プログラムを動かしてみて下さい！
またわからないことがあれば、気軽に連絡してください。

2017/07/13 13:32 "Kilometer0101" <notifications@github.com>:

qiitaから来ました。
興味があって使ってみたいのですが、

pip install git+URL

でインストールできますでしょうか？
手元では、Anaconda 4.3.1を使っていますが、setup.py egg_info: でエラーがで出てしまいます。

Complete output from command python setup.py egg_info:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/km/anaconda/lib/python3.6/tokenize.py", line 452, in open
    buffer = _builtin_open(filename, 'rb')
FileNotFoundError: [Errno 2] No such file or directory:
'/private/var/folders/nk/plk5zj6941sgpvrpvq2h5l500000gn/T/pip-3tbs8wio-build/setup.py'

ご示唆いただけますでしょうか。
当方、Python素人な質問で申し訳在りません。

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/aratakokubun/GraphBasedSegmentationWithUnionFind/issues/1>,
or mute the thread
